name: CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-18.04


    steps:

    - uses: actions/checkout@v2
      
    - name: Use Java8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8

    - name: Build debug APK
      run: bash ./gradlew assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/apk/release/app-release-unsigned.apk
